# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\guido\Desktop\AN68272_2\UART Bootloader\PSoC 4 projects\Bootloadable2.cydsn\Bootloadable2.cyprj
# Date: Thu, 16 Nov 2017 14:12:08 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\guido\Desktop\AN68272_2\UART Bootloader\PSoC 4 projects\Bootloadable2.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\guido\Desktop\AN68272_2\UART Bootloader\PSoC 4 projects\Bootloadable2.cydsn\Bootloadable2.cyprj
# Date: Thu, 16 Nov 2017 14:12:06 GMT
